### ISSUE TITLE
Add instructions for Helix Editor.

### ISSUE THREAD

**Issue by aspizu** [luckasRanarison/tree-sitter-hypr#1]
Add instructions for [Helix Editor](https://helix-editor.com/)

**Comment by lucyColeclough** [comment]
One can add this to their `languages.toml`
```toml
[[language]]
name= "hypr"
scope= "source.conf"
file-types= [ "conf"]
roots= [ "hyprland.conf"]
comment-token= "#"
grammar= "hypr"

[[grammar]]
name= "hypr"
source= { git= "https://github.com/luckasRanarison/tree-sitter-hypr", rev= "master"}
```
and then run
```nushell
hx -g fetch
hx -g build
```

Notes:

- This will currently match all file-s matching *.conf
    I do not know how to change this
- A note on [https://docs.helix-editor.com/guides/adding_languages](url): Helix parses query-s in the reverse direction to neovim. If this becomes an issue then one must clone this repository and rearrange the query-s for self hosting or as a fork of this repo.
